### ISSUE TITLE
Missing Blocks

### ISSUE THREAD

**Issue by AcesGamingUK** [JEFF-Media-GbR/Spigot-BestTools#1]
Mossy Slab
Polished Basalt
Basalt bricks
Polished Blackstone

- > Slab
- > Stairs

Chiseled Polished Blackstone
Glowstone
Nether Bricks
Nether Gold Ore
Blackstone bricks 

> - Stairs
> - Slab

**Comment by mfnalex** [comment]
thanks, I will start to go through this list in an hour or so. Feel free to expand it^^

**Comment by mfnalex** [comment]
btw slabs should be fixed with the latest snapshot

**Comment by AcesGamingUK** [comment]
Terracotta 
Both Nylium
Both Sponge
Both Piston
Chorus Plant

**Comment by AcesGamingUK** [comment]
carved pumpkin
Some infested block (broke to fast didn't see exactly what ones sorry)
Endstone Bricks
Crimson stairs
Warped Stairs
Chiseled Quartz
Quartz Pillar
Quartz Stairs

**Comment by AcesGamingUK** [comment]
coral block - All
Observer
Nether wart block
Warped wart Block
Magma Block
Prismarine + Stairs
Prismarine bricks + Stairs
