### ISSUE TITLE
Potions & Stews

### ISSUE THREAD

**Issue by Christofmeg** [JEFF-Media-GbR/Spigot-BestTools#10]
Hi!

Could you add a blacklist or something to limit what the refill option applies to?

This warning is the result of eating stews and drinking potions.

![besttools_refill](https://user-images.githubusercontent.com/4357405/88951891-e6f58980-d296-11ea-8a1a-dd79c154ea62.PNG)

BestTools 1.6.2.

**Comment by mfnalex** [comment]
you probably have stacked stews, right? Yes, I can add a blacklist soon :)

**Comment by Christofmeg** [comment]
Actually no, I had 1 stew in my inv and 1 in my hotbar.
But thanks!

**Comment by mfnalex** [comment]
ah ok that makes sense, because the slot where /refill think it should be empty now still has the stew inside, same with potions. I might just add an option to move the empty bowls/bottles back into the inventory, or do you need the blacklist for other stuff as well?

**Comment by mfnalex** [comment]
Fixed in https://github.com/JEFF-Media-GbR/Spigot-BestTools/commit/1ee04b513993504b0ef59d4f1077f358cc8cfa80 (version 1.8.0)
