### ISSUE TITLE
Chinese translate update

### ISSUE THREAD

**Issue by Pau1am** [JEFF-Media-GbR/Spigot-BestTools#11]
##### Chinese
message-besttools-enabled: "&7自动切换最佳工具 &a已启用&7."
message-besttools-disabled: "&7自动切换最佳工具 &c已禁用&7."
message-refill-enabled: "&7自动填充方块 &a已启用&7."
message-refill-disabled: "&7自动填充方块 &c已禁用&7."
message-besttools-usage: "&7提示: 输入指令 &6/besttools&7 或 &6/bt&7 可以在破坏任意方块时自动切换至最佳工具."
message-refill-usage: "&7提示: 输入指令 &6/refill&7 或 &6/rf&7 可以从背包里自动填充手中放置完的物品."
message-hotbar-only-enabled: "&7自动切换最佳工具 仅会根据快捷栏切换工具."
message-hotbar-only-disabled: "&7自动切换最佳工具 会根据背包内的所有物品切换工具."
gui-favorite-slot: "设置你的想要工具栏位"
gui-favorite-slot-lore: "如果你的快捷栏已满,自动工具系统会从你的背包中选取工具置于该工具栏位中"
gui-besttools-lore: "在破坏方块时自动选择最佳工具."
gui-hotbar-lore: "启用此项后, 插件只会选取你快捷栏中的最佳工具,而非整个背包内的最佳工具."
gui-refill-lore: "在放置方块时自动选择最佳方块."

**Comment by Pau1am** [comment]
In addition, I suggest adding a new folder for language files, and you can select the language through config, which may be more convenient

**Comment by mfnalex** [comment]
Thanks!

> In addition, I suggest adding a new folder for language files, and you can select the language through config, which may be more convenient

That would break existing configs, which I try to avoid.
