### ISSUE TITLE
Compatibility issues with heads.

### ISSUE THREAD

**Issue by ErythroCraft** [JEFF-Media-GbR/Spigot-BestTools#14]
Ich habe das Plugin auf meinem Server installiert und so eingestellt, dass es blöcke aus dem Inventar ersetz.
Zusätzliche verwende ich die Plugins MobHunt und CommandPannels. 
Bei CommandPannels ist der Slot fest Belegt und der Kopf nicht verschiebbar.
Um Geld in die Bank einzuzahlen, muss der Spieler mit dem eingesammeltem BagOfGold mit der rechten Maustaste auf ein schild klicken.
Sobald ein Spieler alles Geld eingezahlt hat, wird der Kopf von CommandPannels auf den Platz verschoben an dem vorher das BagOfGold item war.

I installed the plugin on my server and set it to replace blocks from my inventory.
I also use the MobHunt and CommandPannels plugins.
With CommandPannels, the slot is permanently occupied and the head cannot be moved.
To deposit money into the bank, the player with the collected BagOfGold must right-click on a sign.
As soon as a player has deposited all the money, the CommandPannels head is moved to the place where the BagOfGold item was previously.

**Comment by mfnalex** [comment]
Wo genau ist denn das Problem?
