### ISSUE TITLE
[BUG] console spam

### ISSUE THREAD

**Issue by larssieboy18** [JEFF-Media-GbR/Spigot-BestTools#15]
Hi,

I haven't heard that it broke the functionality, but this happened inside of the console when people were trying BestTools out:
https://bin.bloom.host/iritovewus.sql. Would it be possible to fix it or am I doing something wrong?

**Comment by mfnalex** [comment]
Hi, that looks like your plugin .jar file is corrupted or something. Please redownload the latest release and properly restart (NOT reload) your server. If the problem persists, I will look into it :)

**Comment by Panic3564** [comment]
ah okay. The old version is still loaded, but I already have the new jar included in my server plugins folder and deleted the previous version, so that might be why it is doing this. Will let you know if it is acting up again

**Comment by mfnalex** [comment]
Anything new?

**Comment by Panic3564** [comment]
Hi there,

No more issues! Thanks :)
