### ISSUE TITLE
Missing block part 2

### ISSUE THREAD

**Issue by AcesGamingUK** [JEFF-Media-GbR/Spigot-BestTools#2]
~~Terracotta (All Colored, All Glazed. Normal is fine)
Both Nylium
Both Sponge
Both Piston
Chorus Plant
Chorus flower
All Purpur blocks~~

~~carved pumpkin
Some infested block (broke to fast didn't see exactly what ones sorry)
Endstone Bricks~~
Crimson stairs
Warped Stairs
Chiseled Quartz
Quartz Pillar
Quartz Stairs
haybale

coral block - All
Observer
Nether wart block
Warped wart Block
Magma Block
Prismarine + Stairs
Prismarine bricks + Stairs

**Comment by mfnalex** [comment]
THank you, will be added :)

**Comment by mfnalex** [comment]
Crimson stairs are wooden, so Axe, right? I couldnt find anything in the wiki yet

**Comment by AcesGamingUK** [comment]
wood is correct
i used https://minecraft.gamepedia.com/`block`
to double check items needed tools
