### ISSUE TITLE
Error messages (EntityDamageByEntityEvent) cropping up with unknown in-game impact

### ISSUE THREAD

**Issue by SleepyCatten** [JEFF-Media-GbR/Spigot-BestTools#20]
Good day,

Sorry to trouble you. I was checking the server logs on a test server and saw multiple Best Tools errors. I've uploaded the entire log here:
https://gist.github.com/SleepyCatten/57f2cbce037181c4d3b62f26ef498648

This on a Paper 133 server with the following plugins/datapacks:

Plugins (18): AngelChest, ArmoredElytra, BestTools, ChestSort, CoreProtect, Drop2InventoryPlus, HolographicDisplays, LuckPerms, PetMaster, PluralKitMC, ProNouns, ProtocolLib, RoseStacker, StackableItems, UltimateTimber, Vault, ViewDistanceTweaks, voicechat

There are 21 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/anti enderman grief v1.1.2.zip (world)], [file/coordinates hud v1.2.2.zip (world)], [file/durability ping v1.1.2.zip (world)], [file/multiplayer sleep v2.6.2.zip (world)], [file/player head drops v1.1.2.zip (world)], [file/redstone rotation wrench v1.1.3.zip (world)], [file/silence mobs v1.1.2.zip (world)], [file/terracotta rotation wrench v1.1.3.zip (world)], [file/more mob heads v2.9.4.zip (world)], [file/dragon drops v1.3.2.zip (world)], [file/double shulker shells v1.3.2.zip (world)], [file/armor statues v2.8.3.zip (world)], [file/respawning-pets-e630.zip (world)], [file/unlock all recipes v2.0.3.zip (world)], [file/global-trades.zip (world)], [file/afk display v1.1.2.zip (world)], [file/nether portal coords v1.1.2.zip (world)], [file/track raw statistics v1.5.2.zip (world)], [file/track statistics v1.1.3.zip (world)]

Apologies in advance for probably not putting sufficient detail!

**Comment by mfnalex** [comment]
Hi, does this happen for all players? If so, check their /bt gui settings: do they have a favorite slot set in the GUI?

**Comment by mfnalex** [comment]
Actually this was fixed a long time ago but it can still happen when players still have broken playerconfig files. Please stop your server, rename the BestTools' playerdata folder to playerdata2, and see if it still happens

**Comment by SleepyCatten** [comment]
Hi! We've just started a brand new 1.18.1 server, so it seems odd that the player files could be broken already. The issue only seems to crop up if the default slot is set to -1

'# The preferred slot where BestTools should move the tool if it's not in the hotbar
'# and hotbar-only is set to false. Must be a number between 0 (leftmost hotbar slot)
'# and 8 (rightmost hotbar slot)
'# Set this to -1 to always use the player's current slot
favorite-slot: -1

Setting it to a number between 0 and 8 seems to stop the error occurring, but then loses the ability for the tool to go into the slot where it disappeared from.

**Comment by mfnalex** [comment]
Hm I actually thought I'd fix this. Can you check whether this happens maybe only when
1. Mining blocks
2. Attacking mobs
3. or both?

**Comment by SleepyCatten** [comment]
Hi. Sorry for the slow reply. I've been trying to replicate this on a test server with just mining blocks and, as of yet, I have yet to be able to replicate it 😖 From memory, the errors seemed to be occurring during combat. I'll keep trying to replicate, but I wanted to respond to let you know I wasn't ignoring the request.

**Comment by SleepyCatten** [comment]
Managed to replicate the issue. It occurs when attacking mobs.

This is the output from the server console log:
https://gist.github.com/SleepyCatten/0f115ddb21300fe27971fe86374e46d2

This is the settings for BestTools:
https://gist.github.com/SleepyCatten/eebef8b96a76aff108f4b2e96edb77b8

This are my player settings:
bestToolsEnabled: true
hotbarOnly: false
refillEnabled: true
hasSeenBestToolsMessage: true
hasSeenRefillMessage: true
favoriteSlot: -1
swordOnMobs: true
blacklist: []

My hotbar was:
1 Sword
2 Pickaxe
3 Axe
4 Shovel
5 Hoe
6 Dirt
7 Empty
8 Torches
9 Cooked chicken

**Comment by mfnalex** [comment]
Thanks, that's very helpful! I'll get it fixed tomorrow (today), it's 7 am and I gotta go to bed lol

**Comment by SleepyCatten** [comment]
Thank you kindly! No mad rush though: sleep is important 💟

**Comment by mfnalex** [comment]
Should be fixed since the last update
