### ISSUE TITLE
Blacklist Suggest

### ISSUE THREAD

**Issue by AcesGamingUK** [JEFF-Media-GbR/Spigot-BestTools#5]
the ability for admin/owner to blacklist certain items from triggering auto tool
Example Scenario
Signs.
I'm trying to remove a "click to sell" sign with a bare hand,
auto-tool triggers ad replaces hand with unbreaking 3, mending, Eff 5 netherite axe.... **PooF**.. sells axe
not that it actually happened or anything 
![bitmoji](https://sdk.bitmoji.com/render/panel/d3925c44-e395-4edd-8978-158a2b25378a-afe6accd-0a9e-455e-b144-baf6b924c649-v1.png?transparent=1&palette=1&width=246)

**Comment by mfnalex** [comment]
I have added a blacklist now, it will work exactly like in InvUnload, except that the command is /bt bl or /besttools blacklist. I will test it a bit and then release it

**Comment by mfnalex** [comment]
added in 1.6.0
