### ISSUE TITLE
[Suggest] Do not switch tools during battle

### ISSUE THREAD

**Issue by Pau1am** [JEFF-Media-GbR/Spigot-BestTools#8]
I think it should be detected whether the player is fighting when BestTool is enabled. If the player is fighting, the switching of the tool should be temporarily prohibited to prevent the player from accidentally touching other blocks and switching the tool.

**Comment by mfnalex** [comment]
Good idea. Maybe I just disable besttools when the player holds some kind of weapon, like bow, sword, trident, crossbow?

**Comment by mfnalex** [comment]
Added in 1.3.0 :)
