### ISSUE TITLE
is possible to have default permission instead 

### ISSUE THREAD

**Issue by johnneijzen** [JEFF-Media-GbR/Spigot-BestTools#9]
can be default permission be that anyone is allow use it but
OP has reload command bit like how grief prevention plugin.yml does

**Comment by mfnalex** [comment]
sorry I don't understand. Can't you just use a permssions plugin?

**Comment by johnneijzen** [comment]
i mean what if you don't want use permission plugin and use just have default permission instead

**Comment by johnneijzen** [comment]
for example https://github.com/TechFortress/GriefPrevention/blob/master/src/main/resources/plugin.yml

**Comment by mfnalex** [comment]
Just install a permissions plugin. https://www.spigotmc.org/resources/1-8-1-16-lightperms.62447/

**Comment by mfnalex** [comment]
IMHO it's bad practice to give players permissions by default. Every admin should decide what player has what permissions. If I would allow every player to use my plugins by default, there would be much more requests to remove that^^

**Comment by johnneijzen** [comment]
yeah i guess but i taught thats what permission plugins are for first place to overwrite default permissions like most plugins have i seen on spigot and bukkit they basically allocated default permission between OP for admin stuff and use and no op for only use of plugin if admin wants to change permissions they would use luckperms or other plugin to change it but it okay i just use your lightperms so i dont have write much
